name: Documenter
on:
  push:
    branches: [master, main]
    tags: [v*]
  pull_request:
    branches: [master, main]
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          RASTERDATASOURCES_PATH: ".."
          GKSwstype: "100"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
